# Generated by Django 5.0.6 on 2024-07-28 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_profile_email_profile_mobile_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cemetery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField()),
                ('location', models.TextField()),
                ('slots', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='rental',
            name='posted_by',
        ),
        migrations.CreateModel(
            name='Kalag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_born', models.TextField()),
                ('date_died', models.TextField()),
                ('address', models.TextField()),
                ('cemetery_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cemetery')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
