# Generated by Django 5.0.6 on 2024-08-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_kalag_cemetery_section_delete_cemetery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cemetery_section', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
