# Generated by Django 5.0.6 on 2024-08-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
