# Generated by Django 5.0.6 on 2024-08-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_plot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalag',
            name='relative_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalag',
            name='relative_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalag',
            name='relative_number',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalag',
            name='relative_relation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
