# Generated by Django 5.0.6 on 2024-08-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_kalag_relative_address_kalag_relative_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grave_level', models.TextField()),
                ('amount', models.IntegerField()),
                ('year', models.IntegerField()),
                ('date_registered', models.DateTimeField()),
                ('status', models.TextField()),
                ('kalag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kalag')),
            ],
        ),
    ]
