# Generated by Django 5.0.6 on 2024-08-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_masterlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalag',
            name='grave_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterlist',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
