# Generated by Django 5.0.6 on 2024-08-24 04:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_kalag_grave_number_alter_masterlist_date_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.FileField(blank=True, null=True, upload_to='background/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])])),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])])),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'mkv', 'wmv', 'mpeg'])])),
                ('kalag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kalag')),
            ],
        ),
    ]
