# Generated by Django 5.0.6 on 2024-08-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_memories'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='speech',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
