# Generated by Django 5.0.6 on 2024-11-08 06:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_kalag_qr_memories_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memories',
            name='qr',
        ),
        migrations.RemoveField(
            model_name='memories',
            name='video',
        ),
        migrations.CreateModel(
            name='ImagesMemories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.FileField(blank=True, null=True, upload_to='background/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])])),
                ('kalag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kalag')),
            ],
        ),
        migrations.CreateModel(
            name='VideosMemories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'mkv', 'wmv', 'mpeg'])])),
                ('kalag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kalag')),
            ],
        ),
    ]
