# Generated by Django 5.0.6 on 2024-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_memories_qr_remove_memories_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='speech',
            field=models.TextField(blank=True, null=True),
        ),
    ]
