# Generated by Django 5.0.6 on 2024-11-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_memories_speech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memories',
            name='kalag',
        ),
        migrations.AddField(
            model_name='memories',
            name='kalag',
            field=models.ManyToManyField(to='api.kalag'),
        ),
    ]
