# Generated by Django 5.0.6 on 2024-11-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_memories_kalag_memories_kalag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='kalag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kalag'),
        ),
    ]
