# Generated by Django 5.0.6 on 2024-11-19 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_memories_kalag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesmemories',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to='background/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'mp4', 'mov', 'mkv', 'wmv', 'mpeg'])]),
        ),
    ]
